package org.lamisplus.modules.central.utility;

import java.text.SimpleDateFormat;
import java.time.LocalDate;

public class ConstantUtility {
    public static final String TEMP_BASE_DIR = System.getProperty("user.dir");
    public static final String TEMP_BATCH_DIR = TEMP_BASE_DIR + "/batch/temp/";
    public static final String TEMP_SERVER_DIR = TEMP_BASE_DIR + "/server/temp/";
    public static final String RADET_FILENAME = "radet.json";
    public static final String EXTRACT_FILENAME = "extract.json";
    public static final String PREP_FILENAME = "prep.json";
    public static final String CLINIC_FILENAME = "clinic.json";
    public static final String PATIENT_FILENAME = "patient.json";
    public static final String LABORATORY_ORDER_FILENAME = "laboratoryOrder.json";
    public static final String LABORATORY_SAMPLE_FILENAME = "laboratorySample.json";
    public static final String LABORATORY_TEST_FILENAME = "laboratoryTest.json";
    public static final String LABORATORY_RESULT_FILENAME = "laboratoryResult.json";
    public static final String PHARMACY_FILENAME = "pharmacy.json";
    public static final String BIOMETRIC_FILENAME = "biometric.json";
    public static final String ENROLLMENT_FILENAME = "hivEnrollment.json";

    public static final String OBSERVATION_FILENAME = "observation.json";
    public static final String STATUS_TRACKER_FILENAME = "statusTracker.json";
    public static final String EAC_FILENAME = "eac.json";
    public static final String HTS_FILENAME = "hts.json";
    public static final String CONTENT_DISPOSITION = "Content-Disposition";
    public static final String ATTACHMENT_FILENAME = "attachment; filename=";
    public static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyyMMddHHmmss");

    public static final String FIRST_NAME = "firstname";
    public static final String SURNAME = "surname";
    public static final String OTHER_NAME = "othername";
    public static final String SEX = "sex";
    public static final String AGE = "age";
    public static final String DATE_OF_BIRTH = "dateofbirth";
    public static final String PHONE_NUMBER = "phonenumber";
    public static final String MARITAL_STATUS = "maritalstatus";
    public static final String LGA_OF_RESIDENCE = "lgaofresidence";
    public static final String STATE_OF_RESIDENCE = "stateofresidence";
    public static final String EDUCATION = "education";
    public static final String OCCUPATION = "occupation";
    public static final String HTS_LATITUDE = "htslatitude";
    public static final String HTS_LONGITUDE = "htslongitude";
    public static final String CLIENT_ADDRESS = "clientaddress";
    public static final String DATE_VISIT = "datevisit";
    public static final String FIRST_TIME_VISIT = "firsttimevisit";
    public static final String NUMBER_OF_CHILDREN = "numberofchildren";
    public static final String NUMBER_OF_WIVES = "numberofwives";
    public static final String INDEX_CLIENT = "indexclient";
    public static final String PREP_OFFERED = "prepoffered";
    public static final String PREP_ACCEPTED = "prepaccepted";
    public static final String PREVIOUSLY_TESTED = "previouslytested";
    public static final String TARGET_GROUP = "targetgroup";
    public static final String REFERRED_FROM = "referredfrom";
    public static final String TESTING_SETTING = "testingsetting";
    public static final String COUNSELING_TYPE = "counselingtype";
    public static final String PREGNANCY_STATUS = "pregnacystatus";
    public static final String BREASTFEEDING = "breastfeeding";
    public static final String INDEX_TYPE = "indextype";
    public static final String IF_RECENCY_TESTING_OPT_IN = "ifrecencytestingoptin";
    public static final String RECENCY_ID = "recencyid";
    public static final String RECENCY_TEST_TYPE = "recencytesttype";
    public static final String RECENCY_TEST_DATE = "recencytestdate";
    public static final String RECENCY_INTERPRETATION = "recencyinterpretation";
    public static final String FINAL_RECENCY_RESULT = "finalrecencyresult";
    public static final String VIRAL_LOAD_RESULT = "viralloadresult";
    public static final String VIRAL_LOAD_SAMPLE_COLLECTION_DATE = "viralloadsamplecollectiondate";
    public static final String VIRAL_LOAD_CONFIRMATION_RESULT = "viralloadconfirmationresult";
    public static final String VIRAL_LOAD_CONFIRMATION_DATE = "viralloadconfirmationdate";
    public static final String ASSESSMENT_CODE = "assessmentcode";
    public static final String MODALITY = "modality";
    public static final String SYPHILIS_TEST_RESULT = "syphilistestresult";
    public static final String HEPATITIS_B_TEST_RESULT = "hepatitisbtestresult";
    public static final String HEPATITIS_C_TEST_RESULT = "hepatitisctestresult";
    public static final String CD4_TYPE = "cd4type";
    public static final String CD4_TEST_RESULT = "cd4testresult";
    public static final String HIV_TEST_RESULT = "hivtestresult";
    public static final String FINAL_HIV_TEST_RESULT = "finalhivtestresult";
    public static final String DATE_OF_HIV_TESTING = "dateofhivtesting";
    public static final String NUMBER_OF_CONDOMS_GIVEN = "numberofcondomsgiven";
    public static final String NUMBER_OF_LUBRICANTS_GIVEN = "numberoflubricantsgiven";

    //PREP variables
    public static final String HIV_ENROLLMENT_DATE = "hivenrollmentdate";
    public static final String DATE_OF_REGISTRATION = "dateofregistration";
    public static final String RESIDENTIAL_STATE = "residentialstate";
    public static final String RESIDENTIAL_LGA = "residentiallga";
    public static final String ADDRESS = "address";
    public static final String PHONE = "phone";
    public static final String BASELINE_REGIMEN = "baselineregimen";
    public static final String BASELINE_SYSTOLIC_BP = "baselinesystolicbp";
    public static final String BASELINE_DIASTOLIC_BP = "baselinediastolicbp";
    public static final String BASELINE_T_WEIGHT = "baselinetweight";
    public static final String BASELINE_HEIGHT = "baselineheight";
    public static final String PREP_COMMENCEMENT_DATE = "prepcommencementdate";
    public static final String BASELINE_URINALYSIS = "baselineurinalysis";
    public static final String BASELINE_URINALYSIS_DATE = "baselineurinalysisdate";
    public static final String BASELINE_CREATININE = "baselinecreatinine";
    public static final String BASELINE_HEPATITIS_B = "baselinehepatitisb";
    public static final String BASELINE_HEPATITIS_C = "baselinehepatitisc";
    public static final String INTERRUPTION_REASON = "interruptionreason";
    public static final String INTERRUPTION_DATE = "interruptiondate";
    public static final String HIV_STATUS_AT_PREP_INITIATION = "hivstatusatprepinitiation";
    public static final String INDICATION_FOR_PREP = "indicationforprep";
    public static final String CURRENT_REGIMEN = "currentregimen";
    public static final String DATE_OF_LAST_PICKUP = "dateoflastpickup";
    public static final String CURRENT_SYSTOLIC_BP = "currentsystolicbp";
    public static final String CURRENT_DIASTOLIC_BP = "currentdiastolicbp";
    public static final String CURRENT_WEIGHT = "currentweight";
    public static final String CURRENT_HEIGHT = "currentheight";
    public static final String CURRENT_URINALYSIS = "currenturinalysis";
    public static final String CURRENT_URINALYSIS_DATE = "currenturinalysisdate";
    public static final String CURRENT_HIV_STATUS = "currenthivstatus";
    public static final String DATE_OF_CURRENT_HIV_STATUS = "dateofcurrenthivstatus";
    public static final String CURRENT_STATUS = "currentstatus";
    public static final String DATE_OF_CURRENT_STATUS = "dateofcurrentstatus";
    public static final String STATE = "state";
    public static final String LGA = "lga";
    public static final String FACILITY_NAME = "facilityName";
    public static final String FACILITY = "facility";
    public static final String DATIM_ID = "datimId";
    public static final String PERSON_UUID = "personUuid";
    public static final String UNIQUE_ID = "uniqueId";
    public static final String HOSPITAL_NUMBER = "hospitalNumber";
    public static final String DATIM_CODE = "datimCode";
    public static final String CLIENT_CODE = "clientCode";
    public static final String PATIENT_ID = "patientId";

    //Clinic
    public static final String VISIT_DATE = "visitDate";
    public static final String CLINICAL_STAGE = "clinicalStage";
    public static final String FUNCTIONAL_STATUS = "functionalStatus";
    public static final String TB_STATUS = "tbStatus";
    public static final String SYSTOLIC = "systolic";
    public static final String DIASTOLIC = "diastolic";
    public static final String ARCHIVED = "archived";
    public static final String CLINIC_PREGNANCY_STATUS = "pregnacystatus";
    public static final String LAST_MODIFIED_DATE = "lastModifiedDate";
    public static final String NEXT_APPOINTMENT = "nextAppointment";
    public static final String LAST_MODIFIED_BY = "lastModifiedBy";
    public static final String BODY_WEIGHT = "bodyWeight";
    public static final String PATIENT_FIRST_NAME = "firstName";
    public static final String PATIENT_OTHER_NAME = "otherName";
    public static final String PATIENT_DATE_OF_BIRTH = "dateOfBirth";
    public static final String PATIENT_DATE_OF_REGISTRATION = "dateOfRegistration";
    public static final String PATIENT_MARITAL_STATUS = "maritalStatus";
    public static final String PATIENT_EDUCATION = "education";
    public static final String PATIENT_RESIDENTIAL_STATE = "residentialState";
    public static final String PATIENT_RESIDENTIAL_LGA = "residentialLga";
    public static final String TOWN = "town";
    public static final String UUID = "uuid";
    public static final String ORDER_DATE = "orderDate";
    public static final String DATE_SAMPLE_COLLECTED = "dateSampleCollected";
    public static final String TEST_ID = "testId";
    public static final String LAB_TEST_NAME = "labTestName";
    public static final String GROUP_NAME = "groupName";
    public static final String VIRAL_LOAD_INDICATION = "viralLoadIndication";
    public static final String UNIT_MEASUREMENT = "unitMeasurement";
    public static final String DATE_ASSAYED = "dateAssayed";
    public static final String DATE_RESULT_REPORTED = "dateResultReported";
    public static final String RESULT_REPORTED = "resultReported";
    public static final String REGIME_NAME = "regimenName";
    public static final String DURATION = "duration";
    public static final String CODE_DESCRIPTION = "codeDescription";
    public static final String VISIT_ID = "visitId";
    public static final String MMD_TYPE = "mmdType";

    public static final String TEMPLATE_TYPE = "templateType";
    public static final String ENROLLMENT_DATE = "enrollmentDate";
    public static final String ISO = "iso";
    public static final String DEVICE_NAME = "deviceName";
    public static final String VERSION_ISO_20 = "versionIso20";
    public static final String IMAGE_QUALITY = "ImageQuality";
    public static final String COUNT = "count";
    public static final String RECAPTURE = "recapture";
    public static final String HASHED = "hashed";
    public static final String TEMPLATE = "template";
    public static final String ID = "id";
    public static final String PERIOD = "period";
    public static final String SUBMISSION_TIME = "submissiontime";
    public static final String DATE_OF_LAST_CRYTOCOCAL_ANTIGEN = "dateOfLastCrytococalAntigen";
    public static final String LAST_CRYTOCOCAL_ANTIGEN = "lastCrytococalAntigen";
    public static final String CASE_MANAGER = "caseManager";
    public static final String VA_CAUSE_OF_DEATH = "vaCauseOfDeath";
    public static final String RADET_DATE_OF_BIRTH1 = "DateOfBirth";
    public static final String RADET_AGE = "Age";
    public static final String RADET_GENDER = "Gender";
    public static final String RADET_TARGET_GROUP1 = "TargetGroup";

    public static final String IPT_COMPLETION_STATUS = "IptCompletionStatus";
    public static final String TB_COMPLETION_DATE = "TbCompletionDate";
    public static final String TB_TREATMENT_START_DATE = "TbTreatmentStartDate";
    public static final String TB_TREATMENT_OUTCOME = "TbTreatmentOutcome";
    public static final String TB_TREATEMENT_TYPE = "TbTreatementType";
    public static final String DATE_OF_TB_DIAGNOSTIC_RESULT_RECEIVED = "DateOfTbDiagnosticResultReceived";
    public static final String DSD_MODEL = "DsdModel";
    public static final String TB_DIAGNOSTIC_RESULT = "TbDiagnosticResult";
    public static final String DATE_OF_TB_SAMPLE_COLLECTION = "DateOfTbSampleCollection";
    public static final String TB_DIAGNOSTIC_TEST_TYPE = "TbDiagnosticTestType";
    public static final String DATE_OF_VL_ELIGIBILITY_STATUS = "DateOfVlEligibilityStatus";
    public static final String VL_ELIGIBILITY_STATUS = "VlEligibilityStatus";
    public static final String CAUSE_OF_DEATH = "CauseOfDeath";
    public static final String CARE_ENTRY = "CareEntry";
    public static final String HOUSEHOLD_NUMBER = "HouseholdNumber";
    public static final String OVC_NUMBER = "OvcNumber";
    public static final String DATE_OF_CERVICAL_CANCER_SCREENING = "DateOfCervicalCancerScreening";
    public static final String CERVICAL_CANCER_TREATMENT_SCREENED = "CervicalCancerTreatmentScreened";
    public static final String CERVICAL_CANCER_SCREENING_METHOD = "CervicalCancerScreeningMethod";
    public static final String CERVICAL_CANCER_SCREENING_TYPE = "CervicalCancerScreeningType";
    public static final String RESULT_OF_CERVICAL_CANCER_SCREENING = "ResultOfCervicalCancerScreening";
    public static final String IPT_TYPE = "IptType";
    public static final String IPT_COMPLETION_DATE = "IptCompletionDate";
    public static final String DATE_OF_IPT_START = "DateOfIptStart";
    public static final String DATE_OF_CURRENT_REGIMEN = "DateOfCurrentRegimen";
    public static final String DATE_OF_TB_SCREENED = "DateOfTbScreened";
    public static final String TB_STATUS1 = "TbStatus";
    public static final String REPEAT_VIRAL_LOAD_RESULT = "RepeatViralLoadResult";
    public static final String DATE_OF_REPEAT_VIRAL_LOAD_EAC_SAMPLE_COLLECTION = "DateOfRepeatViralLoadEACSampleCollection";
    public static final String DATE_OF_REPEAT_VIRAL_LOAD_RESULT = "DateOfRepeatViralLoadResult";
    public static final String DATE_OF_EXTEND_EAC_COMPLETION = "DateOfExtendEACCompletion";
    public static final String DATE_OF_LAST_EAC_SESSION_COMPLETED = "DateOfLastEACSessionCompleted";
    public static final String NUMBER_OF_EAC_SESSION_COMPLETED = "NumberOfEACSessionCompleted";
    public static final String DATE_OF_COMMENCEMENT_OF_EAC = "DateOfCommencementOfEAC";
    public static final String NUMBER_OF_FINGERS_CAPTURED = "NumberOfFingersCaptured";
    public static final String DATE_BIOMETRICS_ENROLLED = "DateBiometricsEnrolled";
    public static final String PREVIOUS_STATUS = "PreviousStatus";
    public static final String PREVIOUS_STATUS_DATE = "PreviousStatusDate";
    public static final String CURRENT_STATUS1 = "CurrentStatus";
    public static final String CURRENT_STATUS_DATE = "CurrentStatusDate";
    public static final String NEXT_PICKUP_DATE = "NextPickupDate";
    public static final String LAST_PICKUP_DATE = "LastPickupDate";
    public static final String MONTHS_OF_ARV_REFILL = "MonthsOfARVRefill";
    public static final String CURRENT_ART_REGIMEN = "CurrentARTRegimen";
    public static final String CURRENT_REGIMEN_LINE = "CurrentRegimenLine";
    public static final String DATE_OF_LAST_CD_4_COUNT = "DateOfLastCd4Count";
    public static final String LAST_CD_4_COUNT = "LastCd4Count";
    public static final String DATE_OF_CURRENT_VIRAL_LOAD_SAMPLE = "DateOfCurrentViralLoadSample";
    public static final String DATE_OF_CURRENT_VIRAL_LOAD = "DateOfCurrentViralLoad";
    public static final String CURRENT_VIRAL_LOAD = "CurrentViralLoad";
    public static final String DATE_OF_VIRAL_LOAD_SAMPLE_COLLECTION = "DateOfViralLoadSampleCollection";
    public static final String VIRAL_LOAD_INDICATION1 = "ViralLoadIndication";
    public static final String CURRENT_WEIGHT1 = "CurrentWeight";
    public static final String CURRENT_CLINICAL_STAGE = "CurrentClinicalStage";
    public static final String PREGNANCY_STATUS1 = "PregnancyStatus";
    public static final String REGIMEN_LINE_AT_START = "RegimenLineAtStart";
    public static final String REGIMEN_AT_START = "RegimenAtStart";
    public static final String ART_START_DATE = "ArtStartDate";
    public static final String ENROLLMENT_SETTING = "EnrollmentSetting";

    public static final String HOUSE_HOLD_NUMBER = "houseHoldNumber";
    public static final String DATE_CONFIRMED_HIV = "dateConfirmedHiv";
    public static final String DATE_STARTED = "dateStarted";
    public static final String ENTRY_POINT = "entryPoint";
    public static final String STATUS_AT_REGISTRATION = "statusAtRegistration";

    public static final String DATA = "data";
    public static final String TYPE = "type";

    public static final String DATE_OF_OBSERVATION = "dateOfObservation";

    public static final String HIV_STATUS = "hivStatus";
    public static final String STATUS_DATE = "statusDate";

    public static final String BARRIERS_OTHERS = "barriersOthers";
    public static final String INTERVENTION_OTHERS = "interventionOthers";
    public static final String INTERVENTION = "intervention";
    public static final String BARRIERS = "barriers";
    public static final String EAC_SESSION_DATE = "eacSessionDate";

    public static final String EAC_UUID = "eacUuid";
    public static final String REFERRAL = "referral";
    public static final String ADHERENCE = "adherence";
    public static final String FOLLOW_UP_DATE = "followUpDate";

    public static final String TREATMENT_METHOD_DATE = "treatmentMethodDate";
    public static final String DATE_OF_ENROLLMENT = "dateOfEnrollment";

    public static final String REGIMEN_LINE = "regimenLine";
    public static final String SAMPLE_TYPE = "sampleType";

    public static final String NO_OF_PARTNERS_ELICITED = "noOfPartnersElicited";
    public static final String OFFERED_INS = "offeredIns";
    public static final String ACCEPTED_INS = "acceptedIns";

    public static final String DSD_MODEL_TYPE = "dsdModelType";
    public static final String PHARMACY_DSD_MODEL = "dsdModel";

    public static final String TEST_UUID = "testUuid";

    public static final String STATUS = "status";

    public static final String HEPATITIS_SCREENING_RESULT = "hepatitisScreeningResult";

    public static final String REGIMEN_TYPE = "regimenType";
    public static final String REGIMEN = "regimen";
    public static final String CD4_COUNT = "cd4Count";
    public static final String CD4_SEMI_QUANTITATIVE = "cd4SemiQuantitative";
    public static final String CD4_FLOW_CYTOMETRY = "cd4FlowCytometry";
    public static final String CLINIC_CD4_TYPE = "cd4Type";
    public static final String IS_COMMENCEMENT = "iscommencement";
    public static final String CD4 = "cd4";
    public static final String CD4_PERCENTAGE = "cd4Percentage";
}
